name: Snake
on:
  workflow_dispatch:
jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@latest
        with:
          username: 'YusufErdemK'
          output: 'snake.svg'
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add snake.svg
          git commit -m "Update snake"
          git push
